version: '3'

services:
  sonarqube:
      image: sonarqube:lts-community
      ports:
        - "9000:9000"
      environment:
        - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/enade
        - SONARQUBE_JDBC_USERNAME=enade
        - SONARQUBE_JDBC_PASSWORD=enade

      depends_on:
        - mysql

  mysql:
      image: mysql:8.0.25
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: enade
