version: '3'

networks:
  gs-network:
    driver: bridge

services:
  sonarqube:
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/mysql
      - SONARQUBE_JDBC_USERNAME=admin
      - SONARQUBE_JDBC_PASSWORD=9132
    networks:
      - gs-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - gs-network

  ngrok:
    image: ngrok/ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: "2hcixsoIwK2IWYqezhbCb5nZdKF_5phP9YVDXv43DfAePwGQC"
    command: http jenkins:8080
    networks:
      - gs-network
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    networks:
      - gs-network
